services:
  # Web Service para la aplicación Flask
  - type: web
    name: taskflow-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: postgresql://taskflow_db_xs9b_user:2JIENWvQTJaldvuqjhZCudwhAuw1z8aX@dpg-d8mb4h0js32c73cf85r0-a/taskflow_db_xs9b
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  # Base de Datos PostgreSQL administrada
  - name: taskflow
    databaseName: taskflow_db_xs9b
    user: taskflow_db_xs9b_user
    plan: free
